// Author: Daniele Giardini - http://www.demigiant.com
// Created: 2015/03/12 15:55

using System;
using System.Collections.Generic;
using DG.Tweening.Core;
using UnityEngine;
#if false // UI_MARKER
using UnityEngine.UI;
#endif

#if false // TEXTMESHPRO_MARKER
using TMPro;
#endif

#pragma warning disable 1591
namespace DG.Tweening
{
    /// <summary>
    /// Attach this to a GameObject to create a tween
    /// </summary>
    [AddComponentMenu("DOTween/DOTween Animation")]
    public class DOTweenAnimation : ABSAnimationComponent
    {
        public enum AnimationType
        {
            None,
            Move,
            LocalMove,
            Rotate,
            LocalRotate,
            Scale,
            Color,
            Fade,
            Text,
            PunchPosition,
            PunchRotation,
            PunchScale,
            ShakePosition,
            ShakeRotation,
            ShakeScale,
            CameraAspect,
            CameraBackgroundColor,
            CameraFieldOfView,
            CameraOrthoSize,
            CameraPixelRect,
            CameraRect,
            UIWidthHeight,
            FillAmount
        }

        public enum TargetType
        {
            Unset,

            Camera,
            CanvasGroup,
            Image,
            Light,
            RectTransform,
            Renderer,
            SpriteRenderer,
            Rigidbody,
            Rigidbody2D,
            Text,
            Transform,

            tk2dBaseSprite,
            tk2dTextMesh,

            TextMeshPro,
            TextMeshProUGUI
        }

        #region EVENTS - EDITOR-ONLY

        /// <summary>Used internally by the editor</summary>
        public static event Action<DOTweenAnimation> OnReset;

        private static void Dispatch_OnReset(DOTweenAnimation anim)
        {
            if (OnReset != null) OnReset(anim);
        }

        #endregion

        public bool targetIsSelf = true; // If FALSE allows to set the target manually

        public GameObject targetGO = null; // Used in case targetIsSelf is FALSE

        // If FALSE always uses the GO containing this DOTweenAnimation (and not the one containing the target) as DOTween's SetTarget target
        public bool tweenTargetIsTargetGO = true;

        public float          delay;
        public float          duration  = 1;
        public Ease           easeType  = Ease.OutQuad;
        public AnimationCurve easeCurve = new(new Keyframe(0, 0), new Keyframe(1, 1));
        public LoopType       loopType  = LoopType.Restart;
        public int            loops     = 1;
        public string         id        = "";
        public bool           isRelative;
        public bool           isFrom;
        public bool           isIndependentUpdate = false;
        public bool           autoKill            = true;
        public bool           autoGenerate        = true; // If TRUE automatically creates the tween at startup

        public bool          isActive = true;
        public bool          isValid;
        public Component     target;
        public AnimationType animationType;
        public TargetType    targetType;
        public TargetType    forcedTargetType; // Used when choosing between multiple targets
        public bool          autoPlay = true;
        public bool          useTargetAsV3;

        public float     endValueFloat;
        public Vector3   endValueV3;
        public Vector2   endValueV2;
        public Color     endValueColor  = new(1, 1, 1, 1);
        public string    endValueString = "";
        public Rect      endValueRect   = new(0, 0, 0, 0);
        public Transform endValueTransform;

        public bool                optionalBool0, optionalBool1;
        public float               optionalFloat0;
        public int                 optionalInt0;
        public RotateMode          optionalRotationMode        = RotateMode.Fast;
        public ScrambleMode        optionalScrambleMode        = ScrambleMode.None;
        public ShakeRandomnessMode optionalShakeRandomnessMode = ShakeRandomnessMode.Full;
        public string              optionalString;

        private          bool        _tweenAutoGenerationCalled; // TRUE after the tweens have been autoGenerated
        private          int         _playCount = -1; // Used when calling DOPlayNext
        private readonly List<Tween> _tmpTweens = new();

        #region Unity Methods

        private void Awake()
        {
            if (!this.isActive || !this.autoGenerate) return;

            if (this.animationType != AnimationType.Move || !this.useTargetAsV3)
            {
                // Don't create tweens if we're using a RectTransform as a Move target,
                // because that will work only inside Start
                this.CreateTween(false, this.autoPlay);
                this._tweenAutoGenerationCalled = true;
            }
        }

        private void Start()
        {
            if (this._tweenAutoGenerationCalled || !this.isActive || !this.autoGenerate) return;

            this.CreateTween(false, this.autoPlay);
            this._tweenAutoGenerationCalled = true;
        }

        private void Reset() { Dispatch_OnReset(this); }

        private void OnDestroy()
        {
            if (this.tween != null && this.tween.active) this.tween.Kill();
            this.tween = null;
        }

        /// <summary>
        /// Creates/recreates the tween without playing it, but first rewinding and killing the existing one if present.
        /// </summary>
        public void RewindThenRecreateTween()
        {
            if (this.tween != null && this.tween.active) this.tween.Rewind();
            this.CreateTween(true, false);
        }

        /// <summary>
        /// Creates/recreates the tween and plays it, first rewinding and killing the existing one if present.
        /// </summary>
        public void RewindThenRecreateTweenAndPlay()
        {
            if (this.tween != null && this.tween.active) this.tween.Rewind();
            this.CreateTween(true, true);
        }

        /// <summary>
        /// Creates/recreates the tween from its target's current value without playing it, but first killing the existing one if present.
        /// </summary>
        public void RecreateTween() { this.CreateTween(true, false); }

        /// <summary>
        /// Creates/recreates the tween from its target's current value and plays it, first killing the existing one if present.
        /// </summary>
        public void RecreateTweenAndPlay() { this.CreateTween(true, true); }

        // Used also by DOTweenAnimationInspector when applying runtime changes and restarting
        /// <summary>
        /// Creates the tween manually (called automatically if AutoGenerate is set in the Inspector)
        /// from its target's current value.
        /// </summary>
        /// <param name="regenerateIfExists">If TRUE and an existing tween was already created (and not killed), kills it and recreates it with the current
        /// parameters. Otherwise, if a tween already exists, does nothing.</param>
        /// <param name="andPlay">If TRUE also plays the tween, otherwise only creates it</param>
        public void CreateTween(bool regenerateIfExists = false, bool andPlay = true)
        {
            if (!this.isValid)
            {
                if (regenerateIfExists) // Called manually: warn users
                    Debug.LogWarning(string.Format("{0} :: This DOTweenAnimation isn't valid and its tween won't be created", this.gameObject.name), this.gameObject);

                return;
            }

            if (this.tween != null)
            {
                if (this.tween.active)
                {
                    if (regenerateIfExists)
                        this.tween.Kill();
                    else return;
                }

                this.tween = null;
            }

//            if (target == null) {
//                Debug.LogWarning(string.Format("{0} :: This DOTweenAnimation's target is NULL, because the animation was created with a DOTween Pro version older than 0.9.255. To fix this, exit Play mode then simply select this object, and it will update automatically", this.gameObject.name), this.gameObject);
//                return;
//            }

            var tweenGO = this.GetTweenGO();
            if (this.target == null || tweenGO == null)
            {
                if (this.targetIsSelf && this.target == null)
                    // Old error caused during upgrade from DOTween Pro 0.9.255
                    Debug.LogWarning(
                        string.Format(
                            "{0} :: This DOTweenAnimation's target is NULL, because the animation was created with a DOTween Pro version older than 0.9.255. To fix this, exit Play mode then simply select this object, and it will update automatically",
                            this.gameObject.name), this.gameObject);
                else
                    // Missing non-self target
                    Debug.LogWarning(string.Format("{0} :: This DOTweenAnimation's target/GameObject is unset: the tween will not be created.", this.gameObject.name), this.gameObject);

                return;
            }

            if (this.forcedTargetType != TargetType.Unset) this.targetType = this.forcedTargetType;
            if (this.targetType == TargetType.Unset)
                // Legacy DOTweenAnimation (made with a version older than 0.9.450) without stored targetType > assign it now
                this.targetType = TypeToDOTargetType(this.target.GetType());

            switch (this.animationType)
            {
                case AnimationType.None:
                    break;
                case AnimationType.Move:
                    if (this.useTargetAsV3)
                    {
                        this.isRelative = false;
                        if (this.endValueTransform == null)
                        {
                            Debug.LogWarning(string.Format("{0} :: This tween's TO target is NULL, a Vector3 of (0,0,0) will be used instead", this.gameObject.name), this.gameObject);
                            this.endValueV3 = Vector3.zero;
                        }
                        else
                        {
#if false // UI_MARKER
                        if (targetType == TargetType.RectTransform) {
                            RectTransform endValueT = endValueTransform as RectTransform;
                            if (endValueT == null) {
                                Debug.LogWarning(string.Format("{0} :: This tween's TO target should be a RectTransform, a Vector3 of (0,0,0) will be used instead", this.gameObject.name), this.gameObject);
                                endValueV3 = Vector3.zero;
                            } else {
                                RectTransform rTarget = target as RectTransform;
                                if (rTarget == null) {
                                    Debug.LogWarning(string.Format("{0} :: This tween's target and TO target are not of the same type. Please reassign the values", this.gameObject.name), this.gameObject);
                                } else {
                                    // Problem: doesn't work inside Awake (ararargh!)
                                    endValueV3 = DOTweenModuleUI.Utils.SwitchToRectTransform(endValueT, rTarget);
                                }
                            }
                        } else
#endif
                            this.endValueV3 = this.endValueTransform.position;
                        }
                    }

                    switch (this.targetType)
                    {
                        case TargetType.Transform:
                            this.tween = ((Transform)this.target).DOMove(this.endValueV3, this.duration, this.optionalBool0);

                            break;
                        case TargetType.RectTransform:
#if false // UI_MARKER
                    tween = ((RectTransform)target).DOAnchorPos3D(endValueV3, duration, optionalBool0);
#else
                            this.tween = ((Transform)this.target).DOMove(this.endValueV3, this.duration, this.optionalBool0);
#endif
                            break;
                        case TargetType.Rigidbody:
#if false // PHYSICS_MARKER
                    tween = ((Rigidbody)target).DOMove(endValueV3, duration, optionalBool0);
#else
                            this.tween = ((Transform)this.target).DOMove(this.endValueV3, this.duration, this.optionalBool0);
#endif
                            break;
                        case TargetType.Rigidbody2D:
#if true // PHYSICS2D_MARKER
                            this.tween = ((Rigidbody2D)this.target).DOMove(this.endValueV3, this.duration, this.optionalBool0);
#else
                    tween = ((Transform)target).DOMove(endValueV3, duration, optionalBool0);
#endif
                            break;
                    }

                    break;
                case AnimationType.LocalMove:
                    this.tween = tweenGO.transform.DOLocalMove(this.endValueV3, this.duration, this.optionalBool0);

                    break;
                case AnimationType.Rotate:
                    switch (this.targetType)
                    {
                        case TargetType.Transform:
                            this.tween = ((Transform)this.target).DORotate(this.endValueV3, this.duration, this.optionalRotationMode);

                            break;
                        case TargetType.Rigidbody:
#if false // PHYSICS_MARKER
                    tween = ((Rigidbody)target).DORotate(endValueV3, duration, optionalRotationMode);
#else
                            this.tween = ((Transform)this.target).DORotate(this.endValueV3, this.duration, this.optionalRotationMode);
#endif
                            break;
                        case TargetType.Rigidbody2D:
#if true // PHYSICS2D_MARKER
                            this.tween = ((Rigidbody2D)this.target).DORotate(this.endValueFloat, this.duration);
#else
                    tween = ((Transform)target).DORotate(endValueV3, duration, optionalRotationMode);
#endif
                            break;
                    }

                    break;
                case AnimationType.LocalRotate:
                    this.tween = tweenGO.transform.DOLocalRotate(this.endValueV3, this.duration, this.optionalRotationMode);

                    break;
                case AnimationType.Scale:
                    switch (this.targetType)
                    {
#if false // TK2D_MARKER
                case TargetType.tk2dTextMesh:
                    tween = ((tk2dTextMesh)target).DOScale(optionalBool0 ? new Vector3(endValueFloat, endValueFloat, endValueFloat) : endValueV3, duration);
                    break;
                case TargetType.tk2dBaseSprite:
                    tween = ((tk2dBaseSprite)target).DOScale(optionalBool0 ? new Vector3(endValueFloat, endValueFloat, endValueFloat) : endValueV3, duration);
                    break;
#endif
                        default:
                            this.tween = tweenGO.transform.DOScale(this.optionalBool0 ? new Vector3(this.endValueFloat, this.endValueFloat, this.endValueFloat) : this.endValueV3, this.duration);

                            break;
                    }

                    break;
#if false // UI_MARKER
            case AnimationType.UIWidthHeight:
                tween = ((RectTransform)target).DOSizeDelta(optionalBool0 ? new Vector2(endValueFloat, endValueFloat) : endValueV2, duration);
                break;
            case AnimationType.FillAmount:
                tween = ((Image)target).DOFillAmount(endValueFloat, duration);
                break;
#endif
                case AnimationType.Color:
                    this.isRelative = false;
                    switch (this.targetType)
                    {
                        case TargetType.Renderer:
                            this.tween = ((Renderer)this.target).material.DOColor(this.endValueColor, this.duration);

                            break;
                        case TargetType.Light:
                            this.tween = ((Light)this.target).DOColor(this.endValueColor, this.duration);

                            break;
#if true // SPRITE_MARKER
                        case TargetType.SpriteRenderer:
                            this.tween = ((SpriteRenderer)this.target).DOColor(this.endValueColor, this.duration);

                            break;
#endif
#if false // UI_MARKER
                case TargetType.Image:
                    tween = ((Graphic)target).DOColor(endValueColor, duration);
                    break;
                case TargetType.Text:
                    tween = ((Text)target).DOColor(endValueColor, duration);
                    break;
#endif
#if false // TK2D_MARKER
                case TargetType.tk2dTextMesh:
                    tween = ((tk2dTextMesh)target).DOColor(endValueColor, duration);
                    break;
                case TargetType.tk2dBaseSprite:
                    tween = ((tk2dBaseSprite)target).DOColor(endValueColor, duration);
                    break;
#endif
#if false // TEXTMESHPRO_MARKER
                case TargetType.TextMeshProUGUI:
                    tween = ((TextMeshProUGUI)target).DOColor(endValueColor, duration);
                    break;
                case TargetType.TextMeshPro:
                    tween = ((TextMeshPro)target).DOColor(endValueColor, duration);
                    break;
#endif
                    }

                    break;
                case AnimationType.Fade:
                    this.isRelative = false;
                    switch (this.targetType)
                    {
                        case TargetType.Renderer:
                            this.tween = ((Renderer)this.target).material.DOFade(this.endValueFloat, this.duration);

                            break;
                        case TargetType.Light:
                            this.tween = ((Light)this.target).DOIntensity(this.endValueFloat, this.duration);

                            break;
#if true // SPRITE_MARKER
                        case TargetType.SpriteRenderer:
                            this.tween = ((SpriteRenderer)this.target).DOFade(this.endValueFloat, this.duration);

                            break;
#endif
#if false // UI_MARKER
                case TargetType.Image:
                    tween = ((Graphic)target).DOFade(endValueFloat, duration);
                    break;
                case TargetType.Text:
                    tween = ((Text)target).DOFade(endValueFloat, duration);
                    break;
                case TargetType.CanvasGroup:
                    tween = ((CanvasGroup)target).DOFade(endValueFloat, duration);
                    break;
#endif
#if false // TK2D_MARKER
                case TargetType.tk2dTextMesh:
                    tween = ((tk2dTextMesh)target).DOFade(endValueFloat, duration);
                    break;
                case TargetType.tk2dBaseSprite:
                    tween = ((tk2dBaseSprite)target).DOFade(endValueFloat, duration);
                    break;
#endif
#if false // TEXTMESHPRO_MARKER
                case TargetType.TextMeshProUGUI:
                    tween = ((TextMeshProUGUI)target).DOFade(endValueFloat, duration);
                    break;
                case TargetType.TextMeshPro:
                    tween = ((TextMeshPro)target).DOFade(endValueFloat, duration);
                    break;
#endif
                    }

                    break;
                case AnimationType.Text:
#if false // UI_MARKER
                switch (targetType) {
                case TargetType.Text:
                    tween = ((Text)target).DOText(endValueString, duration, optionalBool0, optionalScrambleMode, optionalString);
                    break;
                }
#endif
#if false // TK2D_MARKER
                switch (targetType) {
                case TargetType.tk2dTextMesh:
                    tween = ((tk2dTextMesh)target).DOText(endValueString, duration, optionalBool0, optionalScrambleMode, optionalString);
                    break;
                }
#endif
#if false // TEXTMESHPRO_MARKER
                switch (targetType) {
                case TargetType.TextMeshProUGUI:
                    tween = ((TextMeshProUGUI)target).DOText(endValueString, duration, optionalBool0, optionalScrambleMode, optionalString);
                    break;
                case TargetType.TextMeshPro:
                    tween = ((TextMeshPro)target).DOText(endValueString, duration, optionalBool0, optionalScrambleMode, optionalString);
                    break;
                }
#endif
                    break;
                case AnimationType.PunchPosition:
                    switch (this.targetType)
                    {
                        case TargetType.Transform:
                            this.tween = ((Transform)this.target).DOPunchPosition(this.endValueV3, this.duration, this.optionalInt0, this.optionalFloat0, this.optionalBool0);

                            break;
#if false // UI_MARKER
                case TargetType.RectTransform:
                    tween = ((RectTransform)target).DOPunchAnchorPos(endValueV3, duration, optionalInt0, optionalFloat0, optionalBool0);
                    break;
#endif
                    }

                    break;
                case AnimationType.PunchScale:
                    this.tween = tweenGO.transform.DOPunchScale(this.endValueV3, this.duration, this.optionalInt0, this.optionalFloat0);

                    break;
                case AnimationType.PunchRotation:
                    this.tween = tweenGO.transform.DOPunchRotation(this.endValueV3, this.duration, this.optionalInt0, this.optionalFloat0);

                    break;
                case AnimationType.ShakePosition:
                    switch (this.targetType)
                    {
                        case TargetType.Transform:
                            this.tween = ((Transform)this.target).DOShakePosition(this.duration, this.endValueV3, this.optionalInt0, this.optionalFloat0, this.optionalBool0, this.optionalBool1,
                                this.optionalShakeRandomnessMode);

                            break;
#if false // UI_MARKER
                case TargetType.RectTransform:
                    tween = ((RectTransform)target).DOShakeAnchorPos(duration, endValueV3, optionalInt0, optionalFloat0, optionalBool0, optionalBool1, optionalShakeRandomnessMode);
                    break;
#endif
                    }

                    break;
                case AnimationType.ShakeScale:
                    this.tween = tweenGO.transform.DOShakeScale(this.duration, this.endValueV3, this.optionalInt0, this.optionalFloat0, this.optionalBool1, this.optionalShakeRandomnessMode);

                    break;
                case AnimationType.ShakeRotation:
                    this.tween = tweenGO.transform.DOShakeRotation(this.duration, this.endValueV3, this.optionalInt0, this.optionalFloat0, this.optionalBool1, this.optionalShakeRandomnessMode);

                    break;
                case AnimationType.CameraAspect:
                    this.tween = ((Camera)this.target).DOAspect(this.endValueFloat, this.duration);

                    break;
                case AnimationType.CameraBackgroundColor:
                    this.tween = ((Camera)this.target).DOColor(this.endValueColor, this.duration);

                    break;
                case AnimationType.CameraFieldOfView:
                    this.tween = ((Camera)this.target).DOFieldOfView(this.endValueFloat, this.duration);

                    break;
                case AnimationType.CameraOrthoSize:
                    this.tween = ((Camera)this.target).DOOrthoSize(this.endValueFloat, this.duration);

                    break;
                case AnimationType.CameraPixelRect:
                    this.tween = ((Camera)this.target).DOPixelRect(this.endValueRect, this.duration);

                    break;
                case AnimationType.CameraRect:
                    this.tween = ((Camera)this.target).DORect(this.endValueRect, this.duration);

                    break;
            }

            if (this.tween == null) return;

            // Created

            if (this.isFrom)
                ((Tweener)this.tween).From(this.isRelative);
            else
                this.tween.SetRelative(this.isRelative);
            var setTarget = this.GetTweenTarget();
            this.tween.SetTarget(setTarget).SetDelay(this.delay).SetLoops(this.loops, this.loopType).SetAutoKill(this.autoKill)
                .OnKill(() => this.tween = null);
            if (this.isSpeedBased) this.tween.SetSpeedBased();
            if (this.easeType == Ease.INTERNAL_Custom)
                this.tween.SetEase(this.easeCurve);
            else
                this.tween.SetEase(this.easeType);
            if (!string.IsNullOrEmpty(this.id)) this.tween.SetId(this.id);
            this.tween.SetUpdate(this.isIndependentUpdate);

            if (this.hasOnStart)
            {
                if (this.onStart != null) this.tween.OnStart(this.onStart.Invoke);
            }
            else
            {
                this.onStart = null;
            }

            if (this.hasOnPlay)
            {
                if (this.onPlay != null) this.tween.OnPlay(this.onPlay.Invoke);
            }
            else
            {
                this.onPlay = null;
            }

            if (this.hasOnUpdate)
            {
                if (this.onUpdate != null) this.tween.OnUpdate(this.onUpdate.Invoke);
            }
            else
            {
                this.onUpdate = null;
            }

            if (this.hasOnStepComplete)
            {
                if (this.onStepComplete != null) this.tween.OnStepComplete(this.onStepComplete.Invoke);
            }
            else
            {
                this.onStepComplete = null;
            }

            if (this.hasOnComplete)
            {
                if (this.onComplete != null) this.tween.OnComplete(this.onComplete.Invoke);
            }
            else
            {
                this.onComplete = null;
            }

            if (this.hasOnRewind)
            {
                if (this.onRewind != null) this.tween.OnRewind(this.onRewind.Invoke);
            }
            else
            {
                this.onRewind = null;
            }

            if (andPlay)
                this.tween.Play();
            else
                this.tween.Pause();

            if (this.hasOnTweenCreated && this.onTweenCreated != null) this.onTweenCreated.Invoke();
        }

        #endregion

        #region Public Methods

        #region Special

        /// <summary>
        /// Returns the tweens (if generated and not killed) created by all DOTweenAnimations on this gameObject,
        /// in the same order as they appear in the Inspector (top to bottom).<para/>
        /// Note that a tween is generated inside the Awake call (except RectTransform tweens which are generated inside Start),
        /// so this method won't return them before that
        /// </summary>
        public List<Tween> GetTweens()
        {
            var result = new List<Tween>();
            var anims  = this.GetComponents<DOTweenAnimation>();
            foreach (var anim in anims)
                if (anim.tween != null && anim.tween.active)
                    result.Add(anim.tween);

            return result;
        }

        /// <summary>
        /// Sets the animation target (which must be of the same type of the one set in the Inspector).
        /// This is useful if you want to change it BEFORE this <see cref="DOTweenAnimation"/>
        /// creates a tween, while after that it won't have any effect.<para/>
        /// Consider that a <see cref="DOTweenAnimation"/> creates its tween inside its Awake (except for special tweens),
        /// so you will need to sure your code runs before this object's Awake (via ScriptExecutionOrder or enabling/disabling methods)
        /// </summary>
        /// <param name="tweenTarget">
        /// New target for the animation (must be of the same type of the previous one)</param>
        /// <param name="useTweenTargetGameObjectForGroupOperations">If TRUE also uses tweenTarget's gameObject when settings the target-ID of the tween
        /// (which is used with DOPlay/DORestart/etc to apply the same operation on all tweens that have the same target-id).<para/>
        /// You should usually leave this to TRUE if you change the target.
        /// </param>
        public void SetAnimationTarget(Component tweenTarget, bool useTweenTargetGameObjectForGroupOperations = true)
        {
            var newTargetType = TypeToDOTargetType(this.target.GetType());
            if (newTargetType != this.targetType)
            {
                Debug.LogError("DOTweenAnimation ► SetAnimationTarget: the new target is of a different type from the one set in the Inspector");

                return;
            }

            this.target                = tweenTarget;
            this.targetGO              = this.target.gameObject;
            this.tweenTargetIsTargetGO = useTweenTargetGameObjectForGroupOperations;
        }

        #endregion

        /// <summary>
        /// Plays all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOPlay() { DOTween.Play(this.GetTweenTarget()); }

        /// <summary>
        /// Plays backwards all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOPlayBackwards() { DOTween.PlayBackwards(this.GetTweenTarget()); }

        /// <summary>
        /// Plays foward all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOPlayForward() { DOTween.PlayForward(this.GetTweenTarget()); }

        /// <summary>
        /// Pauses all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOPause() { DOTween.Pause(this.GetTweenTarget()); }

        /// <summary>
        /// Pauses/unpauses (depending on the current state) all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOTogglePause() { DOTween.TogglePause(this.GetTweenTarget()); }

        /// <summary>
        /// Rewinds all tweens created by this animation in the correct order
        /// </summary>
        public override void DORewind()
        {
            this._playCount = -1;
            // Rewind using Components order (in case there are multiple animations on the same property)
            var anims = this.gameObject.GetComponents<DOTweenAnimation>();
            for (var i = anims.Length - 1; i > -1; --i)
            {
                var t = anims[i].tween;
                if (t != null && t.IsInitialized()) anims[i].tween.Rewind();
            }
            // DOTween.Rewind(GetTweenTarget());
        }

        /// <summary>
        /// Restarts all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DORestart() { this.DORestart(false); }

        /// <summary>
        /// Restarts all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        /// <param name="fromHere">If TRUE, re-evaluates the tween's start and end values from its current position.
        /// Set it to TRUE when spawning the same DOTweenAnimation in different positions (like when using a pooling system)</param>
        public override void DORestart(bool fromHere)
        {
            this._playCount = -1;
            if (this.tween == null)
            {
                if (Debugger.logPriority > 1) Debugger.LogNullTween(this.tween);

                return;
            }

            if (fromHere && this.isRelative) this.ReEvaluateRelativeTween();
            DOTween.Restart(this.GetTweenTarget());
        }

        /// <summary>
        /// Completes all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOComplete() { DOTween.Complete(this.GetTweenTarget()); }

        /// <summary>
        /// Sends to the given time (and pauses) all the tweens whose target-id is the one set by this animation
        /// </summary>
        /// <param name="time">Time to send the tween to</param>
        public override void DOGotoAndPause(float time) { this.DOGoto(time, false); }

        /// <summary>
        /// Sends to the given time (and plays) all the tweens whose target-id is the one set by this animation
        /// </summary>
        /// <param name="time">Time to send the tween to</param>
        public override void DOGotoAndPlay(float time) { this.DOGoto(time, true); }

        private void DOGoto(float time, bool andPlay)
        {
            this._tmpTweens.Clear();
            DOTween.TweensByTarget(this.GetTweenTarget(), false, this._tmpTweens);
            var len = this._tmpTweens.Count;
            if (len == 0)
                Debugger.LogWarning((andPlay ? "DOGotoAndPlay" : "DoGotoAndPause") + " ► tween doesn't exist");
            else
                for (var i = 0; i < this._tmpTweens.Count; ++i)
                    this._tmpTweens[i].Goto(time, andPlay);

            this._tmpTweens.Clear();
        }

        /// <summary>
        /// Kills all tweens whose target-id is the same as the one set by this animation
        /// </summary>
        public override void DOKill()
        {
            DOTween.Kill(this.GetTweenTarget());
            this.tween = null;
        }

        #region Specifics

        /// <summary>
        /// Plays all tweens with the given ID and whose target-id is the same as the one set by this animation
        /// </summary>
        public void DOPlayById(string id) { DOTween.Play(this.GetTweenTarget(), id); }

        /// <summary>
        /// Plays all tweens with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DOPlayAllById(string id) { DOTween.Play(id); }

        /// <summary>
        /// Pauses all tweens that with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DOPauseAllById(string id) { DOTween.Pause(id); }

        /// <summary>
        /// Plays backwards all tweens with the given ID and whose target-id is the same as the one set by this animation
        /// </summary>
        public void DOPlayBackwardsById(string id) { DOTween.PlayBackwards(this.GetTweenTarget(), id); }

        /// <summary>
        /// Plays backwards all tweens with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DOPlayBackwardsAllById(string id) { DOTween.PlayBackwards(id); }

        /// <summary>
        /// Plays forward all tweens with the given ID and whose target-id is the same as the one set by this animation
        /// </summary>
        public void DOPlayForwardById(string id) { DOTween.PlayForward(this.GetTweenTarget(), id); }

        /// <summary>
        /// Plays forward all tweens with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DOPlayForwardAllById(string id) { DOTween.PlayForward(id); }

        /// <summary>
        /// Plays the next animation on this animation's gameObject (if any)
        /// </summary>
        public void DOPlayNext()
        {
            var anims = this.GetComponents<DOTweenAnimation>();
            while (this._playCount < anims.Length - 1)
            {
                this._playCount++;
                var anim = anims[this._playCount];
                if (anim != null && anim.tween != null && anim.tween.active && !anim.tween.IsPlaying() && !anim.tween.IsComplete())
                {
                    anim.tween.Play();

                    break;
                }
            }
        }

        /// <summary>
        /// Rewinds all tweens with the given ID and whose target-id is the same as the one set by this animation,
        /// then plays the next animation on this animation's gameObject (if any)
        /// </summary>
        public void DORewindAndPlayNext()
        {
            this._playCount = -1;
            DOTween.Rewind(this.GetTweenTarget());
            this.DOPlayNext();
        }

        /// <summary>
        /// Rewinds all tweens with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DORewindAllById(string id)
        {
            this._playCount = -1;
            DOTween.Rewind(id);
        }

        /// <summary>
        /// Restarts all tweens with the given ID and whose target-id is the same as the one set by this animation
        /// </summary>
        public void DORestartById(string id)
        {
            this._playCount = -1;
            DOTween.Restart(this.GetTweenTarget(), id);
        }

        /// <summary>
        /// Restarts all tweens with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DORestartAllById(string id)
        {
            this._playCount = -1;
            DOTween.Restart(id);
        }

        /// <summary>
        /// Kills all tweens with the given ID and whose target-id is the same as the one set by this animation
        /// </summary>
        public void DOKillById(string id) { DOTween.Kill(this.GetTweenTarget(), id); }

        /// <summary>
        /// Kills all tweens with the given ID (regardless of their target gameObject)
        /// </summary>
        public void DOKillAllById(string id) { DOTween.Kill(id); }

        #endregion

        #region Internal (also used by Inspector)

        public static TargetType TypeToDOTargetType(Type t)
        {
            var str                                                           = t.ToString();
            var dotIndex                                                      = str.LastIndexOf(".");
            if (dotIndex != -1) str                                           = str.Substring(dotIndex + 1);
            if (str.IndexOf("Renderer") != -1 && str != "SpriteRenderer") str = "Renderer";
//#if true // PHYSICS_MARKER
//            if (str == "Rigidbody") str = "Transform";
//#endif
//#if true // PHYSICS2D_MARKER
//            if (str == "Rigidbody2D") str = "Transform";
//#endif
#if false // UI_MARKER
//            if (str == "RectTransform") str = "Transform";
            if (str == "RawImage" || str == "Graphic") str = "Image"; // RawImages/Graphics are managed like Images for DOTweenAnimation (color and fade use Graphic target anyway)
#endif
            return (TargetType)Enum.Parse(typeof(TargetType), str);
        }

        // Editor preview system
        /// <summary>
        /// Previews the tween in the editor. Only for DOTween internal usage: don't use otherwise.
        /// </summary>
        public Tween CreateEditorPreview()
        {
            if (Application.isPlaying) return null;

            // CHANGE: first param switched to TRUE otherwise changing an animation and replaying in editor would still play old one
            this.CreateTween(true, this.autoPlay);

            return this.tween;
        }

        #endregion

        #endregion

        #region Private

        /// <summary>
        /// Returns the gameObject whose target component should be animated
        /// </summary>
        /// <returns></returns>
        private GameObject GetTweenGO() { return this.targetIsSelf ? this.gameObject : this.targetGO; }

        /// <summary>
        /// Returns the GameObject which should be used/retrieved for SetTarget
        /// </summary>
        private GameObject GetTweenTarget() { return this.targetIsSelf || !this.tweenTargetIsTargetGO ? this.gameObject : this.targetGO; }

        // Re-evaluate relative position of path
        private void ReEvaluateRelativeTween()
        {
            var tweenGO = this.GetTweenGO();
            if (tweenGO == null)
            {
                Debug.LogWarning(string.Format("{0} :: This DOTweenAnimation's target/GameObject is unset: the tween will not be created.", this.gameObject.name), this.gameObject);

                return;
            }

            if (this.animationType == AnimationType.Move)
                ((Tweener)this.tween).ChangeEndValue(tweenGO.transform.position + this.endValueV3, true);
            else if (this.animationType == AnimationType.LocalMove) ((Tweener)this.tween).ChangeEndValue(tweenGO.transform.localPosition + this.endValueV3, true);
        }

        #endregion
    }

    public static class DOTweenAnimationExtensions
    {
//        // Doesn't work on Win 8.1
//        public static bool IsSameOrSubclassOf(this Type t, Type tBase)
//        {
//            return t.IsSubclassOf(tBase) || t == tBase;
//        }

        public static bool IsSameOrSubclassOf<T>(this Component t) { return t is T; }
    }
}